Migrating default PID gains and filter settings to platform defaults and Kconfig
bitcraze/crazyflie-firmware pull request #1122
Opened 2022-09-29 09:38 UTC by matejkarasek

Until now, PID values have been hardcoded, and could only be changed via permanent_parameters, or in a custom fork. 
This PR enables using platform-specific PID gain values and filter settings.

- PID gains are now defined for each platform individually in the [specific_patform]_defaults.h
- defaults for low pass filter settings are in platform_defaults.h, and can be overridden inside [specific_patform]_defaults.h for each platform if needed
- defines PID_FILTER_ALL and IMPROVED_BARO_Z_HOLD moved to Kconfig

2022-09-29 09:51 UTC, matejkarasek commented
Not sure what is going wrong with the build checks, all platforms build fine locally... Any ideas?

2022-09-30 08:01 UTC, krichardsson commented
After a very quick look (that is it might be completely wrong) I think the problem is that the unit tests can not include the platform_defaults.h file. You probably have to add it to [the unit test config](https://github.com/bitcraze/crazyflie-firmware/blob/master/tools/test/gcc.yml#L23-L71)

You can run the unit tests with `tb test`

I will have mote time to look at the PRs next week

2022-09-30 08:06 UTC, knmcguire commented
Same here:) Please check what is causing the CI to fail

2022-09-30 08:29 UTC, matejkarasek commented
> After a very quick look (that is it might be completely wrong) I think the problem is that the unit tests can not include the platform_defaults.h file. You probably have to add it to [the unit test config](https://github.com/bitcraze/crazyflie-firmware/blob/master/tools/test/gcc.yml#L23-L71)
> 
> You can run the unit tests with `tb test`
> 
> I will have mote time to look at the PRs next week

Thanks for the pointer @krichardsson, will check it out!

2022-09-30 10:24 UTC, matejkarasek commented
So running `tb test` in docker passes all the tests.
But `tb build` fails at same place as the CI.

The unit test config seems to already include the folder where platform_defaults.h is included, so it must be something else 🤔
https://github.com/bitcraze/crazyflie-firmware/blob/b370e20e50106dc10837c97e28404ff5d3efc5ea/tools/test/gcc.yml#L56

2022-10-03 11:03 UTC, krichardsson commented
The problem is not the unit tests, but building the python bindings. You can run them with `tb test_python`.

I think you need to add `"src/platform/interface",` to the include section of bindings/setup.py

2022-10-03 11:22 UTC, krichardsson commented
The call to `commanderGetSetpoint()` in attitude_pid_controller.c is also causing problems, in general it feels a bit "backwards". Maybe you can pass in the value of setpoint.attitudeRate.yaw as a parameter to the function instead?

2022-10-03 13:33 UTC, matejkarasek commented
The build errors are fixed.

> The call to `commanderGetSetpoint()` in attitude_pid_controller.c is also causing problems, in general it feels a bit "backwards". Maybe you can pass in the value of setpoint.attitudeRate.yaw as a parameter to the function instead?

I have removed the feedforward gain (where this is needed) from the current pull request as it can be treated separately.

How would you feel about updating the entire PID structure, such that it includes an extra feedforward gain, and everything is handled by the `pidUpdate(...)` function?
Next to yaw control, we us feed forward gains also in the velocity controller:
https://github.com/bitcraze/crazyflie-firmware/blob/b370e20e50106dc10837c97e28404ff5d3efc5ea/src/modules/src/position_controller_pid.c#L242-L243

2022-10-03 15:14 UTC, matejkarasek commented
The last 2 commits include the feedforward gain in the PID structure, how do you feel about this solution?

2022-10-04 06:56 UTC, krichardsson requested changes
I think it looks good!
The feed forward addition to the the PIDs is a nice feature

2022-10-04 06:56 UTC, krichardsson commented on src/modules/src/attitude_pid_controller.c
> +bool attFiltEnable = ATTITUDE_LPF_ENABLE;
Should these perhaps be static?

2022-10-04 10:12 UTC, matejkarasek commented on src/modules/src/attitude_pid_controller.c
> +bool attFiltEnable = ATTITUDE_LPF_ENABLE;
Yes indeed.... Fixed!

2022-10-04 10:26 UTC, matejkarasek commented
Ok, great to hear!

2022-10-04 14:49 UTC, krichardsson approved these changes
Nice!

2022-10-05 09:15 UTC, merged

2022-10-05 09:15 UTC, krichardsson commented
Merged. Thanks!