Bigquad early access fix
bitcraze/crazyflie-firmware pull request #1131
Opened 2022-10-07 09:23 UTC by victorhook

Enabled external battery voltage measurements to be used as system votlage (useful for Big Quad deck).
Updated power state handling to support lowPower state regardless of platform and if Big Quad deck is connected.
Moved constants from source code to kbuild.

2022-10-07 13:25 UTC, tobbeanton requested changes

2022-10-07 13:25 UTC, tobbeanton commented on src/hal/src/pm_stm32f4.c
> +  if (usingBigQuadDeck)
I would like to remove this dependency and have the BiqQuaddeck driver call a function to enable this behavior instead. Something like pmIgnoreChargedState()

2022-10-13 11:38 UTC, victorhook commented
I agree that it makes more sense to **not** have the dependency in the `pm`.
I made a new public `void pmIgnoreChargedState(bool ignore)` method in `pm` to allow other modules to ignore charging state if needed.

2022-10-14 11:58 UTC, tobbeanton approved these changes

2022-10-14 12:02 UTC, tobbeanton commented
The merge of PR #1132 might create some conflicts.

2022-10-18 14:39 UTC, merged