Adding Flapper platform and handling servomotors
bitcraze/crazyflie-firmware pull request #1132
Opened 2022-10-07 17:53 UTC by matejkarasek

This PR adds a "flapper" platform, together with default settings and gain values.
To enable servomotors, which need a non-zero neutral value, additions were made also to Motors.c and supervisor.c
This is a clean version of #1123 

Finally, cleanup was made after #1121.

2022-10-07 17:55 UTC, matejkarasek commented on bindings/setup.py
> +    # "src/modules/src/power_distribution_flapper.c",
The Python bindings might require some extra work such that they function correctly with the Flapper...
If the second power distribution is included, the build test fails...

2022-10-10 11:18 UTC, tobbeanton commented
Overall I think it looks good! There are two discussion points I can identify though:
1. The servo integration in motors.c is starting to make this file quite large. Maybe it is time to split it up and have a servo.c and maybe a higher level actuator.c file. This is quite a large change though...
2. There is a potential conflicting PR #1131 which is changing the external battery monitoring functionality a bit. Which one is easiest to merge first? Probably PR #1131 since it is smaller.

2022-10-10 12:02 UTC, krichardsson requested changes
I think this generally looks good! 
I mainly have some comments related to ifdefs based on platform, see comments in the code.

2022-10-10 14:24 UTC, matejkarasek commented
> Overall I think it looks good! There are two discussion points I can identify though:

Thanks, @tobbeanton!

> 1. The servo integration in motors.c is starting to make this file quite large. Maybe it is time to split it up and have a servo.c and maybe a higher level actuator.c file. This is quite a large change though...

I agree. In fact I have started working on another PR that should enable more than 4 motors/servos:
https://github.com/flapper-drones/crazyflie-firmware/tree/more_motors

So how about if I introduce the servo & motor separation there?

> 2. There is a potential conflicting PR [Bigquad early access fix #1131](https://github.com/bitcraze/crazyflie-firmware/pull/1131) which is changing the external battery monitoring functionality a bit. Which one is easiest to merge first? Probably PR [Bigquad early access fix #1131](https://github.com/bitcraze/crazyflie-firmware/pull/1131) since it is smaller.

I agree it is easier to merge #1131 first

2022-10-10 14:25 UTC, matejkarasek commented
> I think this generally looks good! I mainly have some comments related to ifdefs based on platform, see comments in the code.

Thanks for the quick review @krichardsson 
Will fix try to fix these soon

2022-10-10 14:33 UTC, matejkarasek commented on src/drivers/src/motors.c
> +uint32_t motor_ratios_stop[] = {0, 0, 0, 0}; // motor-stop PWM signals
yes, indeed...

2022-10-10 14:43 UTC, matejkarasek commented on src/modules/src/supervisor.c
> +  #ifndef SUPERVISOR_TUMBLE_CHECK_DISABLE
True :)

Changed to `SUPERVISOR_TUMBLE_CHECK_ENABLE` which is set to `true` in platform_defaults.h and can be overridden in the defaults of the individual platforms

2022-10-10 17:28 UTC, matejkarasek commented on src/drivers/src/motors.c
> +// For platforms that use servos, set motor numbers and motor stop values
I suspected you may not like this :)

I now created two new functions declared in `power_distribution.h` and implemented in the c of the various power distributions. Would this work?

2022-10-10 17:30 UTC, matejkarasek commented on src/modules/interface/power_distribution.h
> +#ifdef CONFIG_POWER_DISTRIBUTION_FLAPPER
These were used in motors.c, so it was necessary. Not needed anymore...

2022-10-10 18:06 UTC, matejkarasek commented
All the issues are fixed, pls let me know if this works.
And also whether I should do anything about #1131.
Thanks!

2022-10-11 13:13 UTC, matejkarasek commented
@knmcguire Thanks for testing it out! 

Have you trimmed the servos (especially the pitch servo) after the firmware update? It is stored as a permanent parameter, and I have changed the name of the parameter group from "_flapper" to "flapper". So you have to do it after this firmware update...

2022-10-11 13:36 UTC, knmcguire commented
Yes that's it! the flapper.servPitchNeutr had to be adjusted.  It was set to 50 but I had to change it to 58. Let me discuss with @krichardsson if there was anything else but if that is it, we'll merge it soon!

2022-10-11 13:44 UTC, merged

2022-10-11 13:44 UTC, krichardsson commented
Looking nice and clean!
Merged
Welcome flapper!

2022-10-11 13:46 UTC, matejkarasek commented
Wohoo! Awesome, thanks!


> Yes that's it! the flapper.servPitchNeutr had to be adjusted. It was set to 50 but I had to change it to 58. Let me discuss with @krichardsson if there was anything else but if that is it, we'll merge it soon!
The default value is close, but not exact, this varies from Flapper to Flapper (or from servo to servo, to be precise). The same applies for the yaw servo, though there it is less critical...