aideck: Initial ninalink implementation
bitcraze/crazyflie-firmware pull request #856
Opened 2021-09-28 06:04 UTC by jonasdn

Syslink inspiried protocol with the aideck NINA module.

2021-09-30 09:08 UTC, tobbeanton commented
As this is inspired from the syslink I know that we at some point would like it do the communication more efficient. This probably means using DMA in some way. I have not looked into it but it would be good if the protocol works with a DMA scheme, which it might already do.

2021-09-30 14:16 UTC, ataffanel requested changes
Looks good in principle except for the sleep. I am about to review/rewrite Syslink to add flow-control. Lets keep this implementation in sync when we have the new safelinkk (we might even be able to share code between the two procotols?).

2021-09-30 14:16 UTC, ataffanel commented on src/deck/drivers/src/aideck.c
> +        vTaskDelay(M2T(10));
This delay should not be needed and might make it loose packet. Since "uart2GetData" blocks, it will take care of limiting the cpu usage of the task.

2021-12-15 12:55 UTC, knmcguire commented
in light of the latest aideck constructions going on, is this PR still valid?

2022-02-22 15:28 UTC, closed without merging